close all
clear variables
clc

sim_fig = figure('Name', 'COVID-19 Monte Carlo Simulation of a city', ...
                 'NumberTitle', 'off', 'visible', 'off');

filename = "simulation_" + string(floor(posixtime(datetime))) + ".gif";

config = struct('num_days',           100, ...
                'num_humans',         2000, ...
                'city_dimensions',    [1000; 1000], ...
                'show_everyday_plot', true, ...
                'plot_paths',         false, ...
                'save_as_gif',        true, ...
                'sim_fig',            sim_fig, ...
                'filename',           filename);

                   
sim = simulation(config=config);

sim.run();

sim.process_data();

sim.display_data();